### ISSUE TITLE
Doesn't build on clean pull

### ISSUE THREAD

**Issue by erebuswolf** [mircead52/xinputproxy#1]
Hey, I forked the project for my own proxy issue/idea. I immediately ran into a build issue where the project seems to expect a folder to exist outside of the project directory or maybe I'm misunderstanding the error.
 
`2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: The command "del /F C:\Users\Jesse\source\repos\xinputproxy\\..\..\XInput\x64\Debug\XINPUT9_1_0.dll`

I'm not super familiar with VS build system. Any idea what I should be doing here? It seems weird to require a directory structure outside of the repository to have it work.

**Comment by erebuswolf** [comment]
Yeah, I added the folder structure it expected outside the repo and the build worked. Not sure how to edit that or change it so it doesn't work like that. Or make it auto generate the structure.

**Comment by mircead52** [comment]
Hey. That is the Microsoft demo project for XInput I used for testing my implementation.
I'll consider removing the Post-Install commands (they delete the existing dll from that folder and then copy the newly compiled one so that I could run the MS test App)

Creating that folder structure is ok for now. Maybe even ignoring the error would have been ok, since those steps happen only after the build is successful.

I think if you go to the Project Properties -> Build Events -> Post-build Events and delete the command-line, that should fix the error.

Thanks for the heads-up.

**Comment by erebuswolf** [comment]
Ah ok, was wondering how to do that. Also, heads up, this approach is broken in Windows 10 https://superuser.com/questions/1387896/why-does-windows-10-no-longer-load-required-dlls-from-path-and-executable-file

**Comment by mircead52** [comment]
I don't have that option enabled on my machine (I have standard installs of Win10). From what I understand the option is not enabled by default (HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Session Manager/CWDIllegalInDllSearch). Maybe a company laptop would have it enabled by the IT department.

If you are looking into dll injection here is an interesting read from Microsoft for developers to prevent this kind of dll/code injection in their programs; it might be an interesting read for your project:
https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-security

If you are interesting in injecting, have a look into Detours they have all sorts of examples included: https://github.com/microsoft/Detours. I've used it to intercept GetProcAddress WinAPI and return my own functions to the main process without much headaches (This only works if the process is loading the dll dynamically with LoadLibrary - as opposed to compiling against it).

Anyway good luck.
